### ISSUE TITLE
Nested Elements in CSS 

### ISSUE THREAD

**Issue by felipefialho** [harvesthq/chosen#1833]
Hey, how are you?

I am a great fan of your plugin and I use in my projects.

I have one suggestion for improve the CSS code. Avoid use nested elements.

For example.

``` css
.chosen-single div {
    position: absolute;
    top: 0;
    right: 0;
    display: block;
    width: 18px;
    height: 100%;
    b {
        display: block;
        width: 100%;
        height: 100%;
        background: $chosen-sprite no-repeat 0px 2px;
    }
  }
```

This block use of `div` inner `.` Single-chosen, but we could make use of class.

``` css
.chosen-single-inner{
   position: absolute;
    top: 0;
    right: 0;
    display: block;
    width: 18px;
    height: 100%;
}
.chosen-single-select{
    display: block;
    width: 100%;
    height: 100%;
    background: $chosen-sprite no-repeat 0px 2px;
}
```

This improves code performance in browsers.

Are you agree with this approach?

I can develop this suggestions.
