### ISSUE TITLE
iPad : Select option triggers link below

### ISSUE THREAD

**Issue by melinadonati** [harvesthq/chosen#1887]
Hi, I'm getting the same issue as described below (on <a href="http://stackoverflow.com/questions/22520164/jquery-chosen-select-option-triggers-link-with-lower-z-index-when-selected-on-ip">stackoverflow 19 march</a>).
Tapping on an option selects it, but the tap event seems to continue, and after the select list is hidden, it triggers a link that was below the selected option.

<b>Stackoverflow issue description</b>
"I am using jQuery Chosen plugin to style select box #foo. I have a block level link (#bar) which is positioned just below #foo and which has a lower (0) z index. #foo 's options have a z-index of 1010.

On my ipad mini, when I select an option from #foo, the link (#bar) is triggered. I have no issues on an android tablet, and I am not having any problems on any non-touch browser. Just iPad

Here is my code:

```html
<select id="foo">
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
    <option>foo</option>
</select>

<a href="http:www.stackoverflow.com" id="bar">GO!</a>
```
and the CSS

```css
#foo {width:300px;}

#bar {display:block; width:400px; height:100px; color:#FFF; text-align:center; font-size:30px; background:#FF0000; line-height:90px; z-index:0;}
```

<a href="http://jsfiddle.net/356xX/4/">here</a> is my fiddle. The css for jQuery chosen is in the fiddle's external resources.
Thanks for help!
