### ISSUE TITLE
Changing the height of Chosen Select fields

### ISSUE THREAD

**Issue by gitmk** [harvesthq/chosen#235]
What is the best way to change the height of the select drop-downs created by Chosen? On my website, it looks too big and occupies a lot of real estate when we have too many.

Please suggest

**Comment by deltaidea** [comment]
Thanks, can confirm that the previous solution still works:

```CSS
.chosen-drop .chosen-results {
    max-height: 100px;
}
```
