### ISSUE TITLE
Number of options shown - feature request

### ISSUE THREAD

**Issue by pierr0t** [harvesthq/chosen#2400]
Hello,
Unless I am blind, I couldnt find an option to decide how many options are visible when activating the drop-down select. Sometimes it makes sense to make the drop-down a little taller so the last 2 options are visible at all time. I already suppressed the search with the disable_search_threshold, I tried some CSS to make the text smaller but I still have one option not visible at the bottom although I have plenty of space (whatever the device). I know chosen is built upon the system-generated select but everything is transformed into ul/li so I guess this should be feasable ... I saw a recent max_shown_results created 14 days ago which seems quite the opposite, I would need a min_shown_results ...
Thks for reading me.
Pierre

**Comment by tjschuck** [comment]
You're just trying to change the size of the dropdown itself so it initially shows more/fewer options before scroll?  You can do that with CSS:

```css
.chosen-container .chosen-results {
  max-height: 500px;  /* This defaults to 240px -- make it whatever you'd like */
} 
```
