### ISSUE TITLE
Add specific class on search-choice in order to customize choices widget

### ISSUE THREAD

**Issue by cbeauchesne** [harvesthq/chosen#2812]
Hello,

I would like to customize choice `<li>` elements. My labels are quite longs, and my users perfectly knows some shortcuts icons, so it would be much more pretty to show only icons.

From :
![image](https://cloud.githubusercontent.com/assets/11915659/25082747/0b7c4e02-2353-11e7-8c31-fa89c875c189.png)

To :
![image](https://cloud.githubusercontent.com/assets/11915659/25082707/d427b9be-2352-11e7-9d45-746491894635.png)

The solution I've implemented is a modification of this https://github.com/harvesthq/chosen/blob/master/coffee/chosen.jquery.coffee#L305 by adding a `search-choice-" + item.array_index` that allow my to add CSS to hide span, and add a :before image.

```CSS
.search-choice span{
display:none
}

.search-choice-1:before{
content : url(/static/img/paragliding-16x16.png);
}

.search-choice-2:before{
content : url(/static/img/skitouring-16x16.png);
}

.search-choice-3:before{
content : url(/static/img/rock_climbing-16x16.png);
}
```

Would it be relevant to include this, or is there a better way? (in this case, sorry for the issue, I've found nothing on SO).

Regards
