### ISSUE TITLE
After selecting an item in chosen with mobile device, cursor is left on the page

### ISSUE THREAD

**Issue by cgatesman** [harvesthq/chosen#2912]
chosen v1.8.2

When you select an item in a chosen dropdown with a mobile device, a cursor is left blinking below the chosen.

### Steps to reproduce

  1. Using a mobile device, drop down a chosen
  2. Select an item in the dropdown
  3. You will see a cursor blinking below the chosen (see attached video)

You can reproduce this on the [Chosen demo page](http://harvesthq.github.io/chosen/) (as seen in video).

[Video showing the problem](https://s3.amazonaws.com/uploads.hipchat.com/48031/626958/d9fSq5HOS4uqINp/IMG_0071.TRIM.MOV)

![img_0604cb0c79c9-1](https://user-images.githubusercontent.com/6276072/32108135-b447f386-bafe-11e7-994e-f73f8608dba8.jpeg)

### Environment

  - iOS 11 on various devices

**Comment by cgatesman** [comment]
I suspect this is related to the fact that chosen is using the deprecated `clip` CSS property for showing and hiding the dropdown.

https://developer.mozilla.org/en-US/docs/Web/CSS/clip

**Comment by cgatesman** [comment]
As a workaround, I included the following CSS in my project.  I'm not sure if this catches all cases, but appears to fix all my use cases:

```scss
.chosen-container .chosen-search-input[readonly] {
  display: none;
}

.chosen-container:not(.chosen-with-drop) .chosen-drop .chosen-search-input {
  display: none;
}
```
