### ISSUE TITLE
Add user-select:none to prevent text selection when "dragging" between options

### ISSUE THREAD

**Issue by nicknotfound** [harvesthq/chosen#292]
When making a selection with the mouse pointer, a normal select box chooses the item you're on when the mouse button is released (which can be different from the item you're on when the mouse button is pressed down).  This behavior is the same in a Chosen select box as well (nicely done!).  However, when pressing the mouse and dragging it to another item, the text of the items you drag past is selected.

This can be prevented by simply adding the following CSS to the `.chzn-container .chzn-results li` selector:

``` css
.chzn-container .chzn-results li {
  /* ... */
  -webkit-user-select: none;
     -moz-user-select: none;
       -o-user-select: none;
          user-select: none;
}
```

Also, thanks for such an awesome library!
