### ISSUE TITLE
Icons don't work correctly

### ISSUE THREAD

**Issue by LuizMoratelli** [harvesthq/chosen#3055]
Icons, e.g. in selects, don't appear correctly for me.

### Steps to reproduce
  1. Create a select or any element that has icons.

  2. Look to icons

As you can see: http://prntscr.com/nsse0o

### Expected behavior

Icons display correctly.

### Actual behavior

Icons are not being displayed correctly.

### Environment

  - **Chosen Version**: 1.8.7

  - **jQuery or Prototype Version**: 3.3.1

  - **Browser and Version**: Chrome 74.0.3729.169 64bits

  - **OS and Version**: Windows 10 KB4023057

### Additional information

I used CSS to fix, something like this:
```CSS
.chosen-container-multi .chosen-choices li.search-choice .search-choice-close {
    // [...]
    background-size: 52px 37px !important;
}
```

After my "CSS fix": http://prntscr.com/nsscfn

Ps.: using a retina screen (MacBook Pro) works correctly.
