### ISSUE TITLE
Styling issue when using Formalize

### ISSUE THREAD

**Issue by parshap** [harvesthq/chosen#361]
I found that there is a minor styling issue with the search input field when using [Formalize](http://formalize.me/).

The following seems to put the styles back to what Chosen is expecting:

``` css
.chzn-container-single .chzn-search input {
    moz-box-sizing: content-box;
    webkit-box-sizing: content-box;
    ms-box-sizing: content-box;
    box-sizing: content-box;

    height: auto;
}
```

It might be a good idea to explicitly set the default styles you are expecting as to not run into conflicts like this. (Of course, who would have expected `box-sizing` to change?)
